# docker-compose.yml
version: '3.8'

services:
  backend:
    build: .
    container_name: kp_backend
    ports:
      - "3000:8000"  # ← Измени первое число (внешний порт)
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./kp.db
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
